export interface TemplateActivity {
  title: string;
  type: string;
  day: number;
  startTime?: string;
  endTime?: string;
  location?: string;
  address?: string;
  description?: string;
  cost?: number;
}

export interface RouteTemplate {
  id: string;
  title: string;
  destination: string;
  country: string;
  continent: string;
  flag: string;
  duration: number;
  coverImage: string;
  description: string;
  tags: string[];
  highlights: string[];
  currency: string;
  estimatedBudget: string;
  activities: TemplateActivity[];
}

export const ROUTE_TEMPLATES: RouteTemplate[] = [
  {
    id: "paris-classic",
    title: "Paris Clássica",
    destination: "Paris, França",
    country: "França",
    continent: "Europa",
    flag: "🇫🇷",
    duration: 5,
    coverImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=500&fit=crop",
    description: "Descubra a cidade-luz com visitas aos monumentos icônicos, culinária refinada e uma dose de arte e cultura parisiense.",
    tags: ["cultura", "arte", "gastronomia", "história", "romântico"],
    highlights: [
      "Torre Eiffel ao pôr do sol",
      "Museu do Louvre",
      "Passeio pelo Rio Sena",
      "Sacré-Cœur em Montmartre",
    ],
    currency: "EUR",
    estimatedBudget: "€1.500 – €2.500",
    activities: [
      {
        title: "Chegada e check-in no hotel",
        type: "OTHER",
        day: 1,
        startTime: "14:00",
        endTime: "16:00",
        location: "Paris CDG",
        description: "Chegada no aeroporto Charles de Gaulle e traslado para o hotel.",
      },
      {
        title: "Passeio pelos Campos Elíseos",
        type: "ACTIVITY",
        day: 1,
        startTime: "17:00",
        endTime: "19:30",
        location: "Avenue des Champs-Élysées",
        address: "Av. des Champs-Élysées, Paris",
        description: "Primeira caminhada pela famosa avenida até o Arco do Triunfo.",
        cost: 0,
      },
      {
        title: "Jantar em bistrô francês",
        type: "MEAL",
        day: 1,
        startTime: "20:00",
        endTime: "22:00",
        location: "Le Comptoir du Relais",
        address: "9 Carrefour de l'Odéon, Paris",
        description: "Boeuf bourguignon e vinho tinto em ambiente parisiense autêntico.",
        cost: 45,
      },
      {
        title: "Torre Eiffel",
        type: "ACTIVITY",
        day: 2,
        startTime: "09:00",
        endTime: "12:00",
        location: "Torre Eiffel",
        address: "Champ de Mars, 5 Av. Anatole France, Paris",
        description: "Subida à Torre Eiffel com vista panorâmica da cidade. Reserve antecipado.",
        cost: 30,
      },
      {
        title: "Almoço no Champ de Mars",
        type: "MEAL",
        day: 2,
        startTime: "12:30",
        endTime: "13:30",
        location: "Champ de Mars",
        description: "Piquenique com queijos, baguete e vinho no parque.",
        cost: 20,
      },
      {
        title: "Museu do Louvre",
        type: "ACTIVITY",
        day: 2,
        startTime: "14:00",
        endTime: "18:00",
        location: "Musée du Louvre",
        address: "Rue de Rivoli, Paris",
        description: "Visita ao maior museu do mundo. Não perca Mona Lisa, Vênus de Milo e Vitória de Samotrácia.",
        cost: 22,
      },
      {
        title: "Montmartre e Sacré-Cœur",
        type: "ACTIVITY",
        day: 3,
        startTime: "09:30",
        endTime: "13:00",
        location: "Sacré-Cœur",
        address: "35 Rue du Chevalier de la Barre, Montmartre, Paris",
        description: "Suba a colina de Montmartre e visite a basílica com vista incrível da cidade.",
        cost: 0,
      },
      {
        title: "Cruzeiro no Rio Sena",
        type: "ACTIVITY",
        day: 3,
        startTime: "15:00",
        endTime: "16:30",
        location: "Bateaux Parisiens",
        address: "Port de la Bourdonnais, Paris",
        description: "Passeio de barco pelo Sena passando pelos principais monumentos.",
        cost: 18,
      },
      {
        title: "Musée d'Orsay",
        type: "ACTIVITY",
        day: 4,
        startTime: "10:00",
        endTime: "13:00",
        location: "Musée d'Orsay",
        address: "1 Rue de la Légion d'Honneur, Paris",
        description: "Impressionismo francês: Monet, Renoir, Van Gogh. Instalado na antiga estação de trem.",
        cost: 16,
      },
      {
        title: "Versalhes — Palácio e Jardins",
        type: "ACTIVITY",
        day: 4,
        startTime: "14:30",
        endTime: "18:30",
        location: "Palácio de Versalhes",
        address: "Place d'Armes, Versailles",
        description: "Excursão ao espetacular palácio e seus jardins geométricos. Tome o RER C.",
        cost: 20,
      },
      {
        title: "Le Marais — gastronomia e compras",
        type: "ACTIVITY",
        day: 5,
        startTime: "10:00",
        endTime: "14:00",
        location: "Le Marais",
        address: "Rue de Bretagne, Paris",
        description: "Bairro histórico com falafel famoso na Rue des Rosiers, galerias e boutiques.",
        cost: 0,
      },
      {
        title: "Despedida com jantar gourmet",
        type: "MEAL",
        day: 5,
        startTime: "19:30",
        endTime: "22:00",
        location: "Septime",
        address: "80 Rue de Charonne, Paris",
        description: "Restaurante estrelado Michelin com menu-degustação da cozinha francesa contemporânea.",
        cost: 90,
      },
    ],
  },
  {
    id: "tokyo-adventure",
    title: "Aventura em Tóquio",
    destination: "Tokyo, Japão",
    country: "Japão",
    continent: "Ásia",
    flag: "🇯🇵",
    duration: 7,
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=500&fit=crop",
    description: "Mergulhe na fascinante mistura de tradição milenar e tecnologia futurística da capital japonesa.",
    tags: ["tecnologia", "cultura", "gastronomia", "anime", "templos"],
    highlights: [
      "Monte Fuji ao amanhecer",
      "Templo Senso-ji em Asakusa",
      "Harajuku e moda japonesa",
      "Shibuya Crossing",
    ],
    currency: "JPY",
    estimatedBudget: "¥150.000 – ¥250.000",
    activities: [
      {
        title: "Chegada em Narita e traslado",
        type: "OTHER",
        day: 1,
        startTime: "10:00",
        endTime: "14:00",
        location: "Aeroporto Narita",
        description: "Tome o Narita Express até Shinjuku. Compre o IC Card no aeroporto.",
      },
      {
        title: "Shinjuku — chegada e exploração noturna",
        type: "ACTIVITY",
        day: 1,
        startTime: "18:00",
        endTime: "22:00",
        location: "Shinjuku",
        address: "Shinjuku, Tokyo",
        description: "Explore Kabukicho, Golden Gai e os arranha-céus iluminados.",
        cost: 0,
      },
      {
        title: "Senso-ji e Nakamise-dori",
        type: "ACTIVITY",
        day: 2,
        startTime: "08:00",
        endTime: "11:00",
        location: "Senso-ji",
        address: "2-3-1 Asakusa, Taito City, Tokyo",
        description: "Templo budista mais antigo de Tóquio. Chegue cedo para evitar multidões.",
        cost: 0,
      },
      {
        title: "Akihabara — eletrônicos e anime",
        type: "ACTIVITY",
        day: 2,
        startTime: "13:00",
        endTime: "17:00",
        location: "Akihabara",
        address: "Akihabara, Chiyoda, Tokyo",
        description: "Paraíso para tecnologia, mangá, anime e cultura gamer.",
        cost: 50,
      },
      {
        title: "Harajuku e Takeshita Street",
        type: "ACTIVITY",
        day: 3,
        startTime: "10:00",
        endTime: "13:00",
        location: "Harajuku",
        address: "Takeshita St, Harajuku, Shibuya, Tokyo",
        description: "Moda alternativa, crepes coloridos e cultura pop japonesa.",
        cost: 20,
      },
      {
        title: "Meiji Jingu",
        type: "ACTIVITY",
        day: 3,
        startTime: "14:00",
        endTime: "16:00",
        location: "Meiji Jingu",
        address: "1-1 Yoyogikamizonocho, Shibuya, Tokyo",
        description: "Santuário xintoísta dedicado ao Imperador Meiji, rodeado de floresta.",
        cost: 0,
      },
      {
        title: "Shibuya Crossing",
        type: "ACTIVITY",
        day: 3,
        startTime: "19:00",
        endTime: "20:30",
        location: "Shibuya Crossing",
        address: "Shibuya, Tokyo",
        description: "O cruzamento mais movimentado do mundo. Observe do Starbucks da esquina.",
        cost: 0,
      },
      {
        title: "Excursão ao Monte Fuji",
        type: "ACTIVITY",
        day: 4,
        startTime: "07:00",
        endTime: "19:00",
        location: "Monte Fuji",
        address: "Fujinomiya, Shizuoka",
        description: "Subida às 5.ª estação do Fuji ou passeio pelo Lago Kawaguchiko.",
        cost: 60,
      },
      {
        title: "Tsukiji Outer Market — café da manhã",
        type: "MEAL",
        day: 5,
        startTime: "07:00",
        endTime: "09:00",
        location: "Tsukiji Market",
        address: "4-16-2 Tsukiji, Chuo, Tokyo",
        description: "Frutos do mar fresquíssimos, tamagoyaki e sushi da manhã.",
        cost: 25,
      },
      {
        title: "Odaiba — ilha artificial futurista",
        type: "ACTIVITY",
        day: 5,
        startTime: "11:00",
        endTime: "16:00",
        location: "Odaiba",
        address: "Odaiba, Minato, Tokyo",
        description: "Réplica da Estátua da Liberdade, teamLab Borderless, Gundam gigante.",
        cost: 30,
      },
      {
        title: "Museu Ghibli",
        type: "ACTIVITY",
        day: 6,
        startTime: "10:00",
        endTime: "13:00",
        location: "Ghibli Museum",
        address: "1-1-83 Shimorenjaku, Mitaka, Tokyo",
        description: "Museu do estúdio de animação criador de Totoro, Spirited Away. Reserve meses antes.",
        cost: 12,
      },
      {
        title: "Shinjuku Gyoen",
        type: "ACTIVITY",
        day: 6,
        startTime: "14:00",
        endTime: "16:30",
        location: "Shinjuku Gyoen",
        address: "11 Naito-machi, Shinjuku, Tokyo",
        description: "Jardim nacional com seções francesa, inglesa e japonesa. Perfeito para relaxar.",
        cost: 5,
      },
      {
        title: "Janta de ramen em Fuunji",
        type: "MEAL",
        day: 7,
        startTime: "12:00",
        endTime: "13:30",
        location: "Fuunji",
        address: "2-14-3 Yoyogi, Shibuya, Tokyo",
        description: "Um dos melhores tsukemen (ramen de imersão) de Tóquio.",
        cost: 15,
      },
    ],
  },
  {
    id: "new-york-classic",
    title: "Nova York Clássica",
    destination: "Nova York, EUA",
    country: "EUA",
    continent: "Américas",
    flag: "🇺🇸",
    duration: 5,
    coverImage: "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800&h=500&fit=crop",
    description: "A cidade que nunca dorme: arranha-céus, museus de classe mundial, Broadway e a energia única de Manhattan.",
    tags: ["urbano", "cultura", "museus", "teatro", "compras"],
    highlights: [
      "Times Square",
      "Central Park",
      "Metropolitan Museum of Art",
      "Brooklyn Bridge",
    ],
    currency: "USD",
    estimatedBudget: "$1.800 – $3.000",
    activities: [
      {
        title: "Times Square e Broadway",
        type: "ACTIVITY",
        day: 1,
        startTime: "16:00",
        endTime: "19:00",
        location: "Times Square",
        address: "Times Square, Manhattan, New York",
        description: "Chegue no coração de Midtown e sinta a energia de Nova York.",
        cost: 0,
      },
      {
        title: "Show na Broadway",
        type: "EVENT",
        day: 1,
        startTime: "20:00",
        endTime: "22:30",
        location: "Broadway",
        address: "W 45th St, New York",
        description: "Veja um musical icônico. Tente TKTS para ingressos com desconto.",
        cost: 120,
      },
      {
        title: "Central Park — manhã",
        type: "ACTIVITY",
        day: 2,
        startTime: "08:00",
        endTime: "11:00",
        location: "Central Park",
        address: "Central Park, New York",
        description: "Caminhada pelo parque: Bethesda Fountain, Strawberry Fields, Jacqueline Kennedy Reservoir.",
        cost: 0,
      },
      {
        title: "Metropolitan Museum of Art",
        type: "ACTIVITY",
        day: 2,
        startTime: "13:00",
        endTime: "17:00",
        location: "The Met",
        address: "1000 5th Ave, New York",
        description: "Um dos maiores museus do mundo: arte egípcia, impressionismo europeu, moda e mais.",
        cost: 30,
      },
      {
        title: "Estatua da Liberdade e Ellis Island",
        type: "ACTIVITY",
        day: 3,
        startTime: "09:00",
        endTime: "13:30",
        location: "Estatua da Liberdade",
        address: "Liberty Island, New York Harbor",
        description: "Ferry saindo de Battery Park. Reserve a coroa com bastante antecedência.",
        cost: 25,
      },
      {
        title: "Brooklyn Bridge e DUMBO",
        type: "ACTIVITY",
        day: 3,
        startTime: "15:00",
        endTime: "17:30",
        location: "Brooklyn Bridge",
        address: "Brooklyn Bridge, New York",
        description: "Atravesse a ponte a pé e explore o bairro DUMBO com vista da Manhattan skyline.",
        cost: 0,
      },
      {
        title: "Museum of Modern Art (MoMA)",
        type: "ACTIVITY",
        day: 4,
        startTime: "10:00",
        endTime: "13:00",
        location: "MoMA",
        address: "11 W 53rd St, New York",
        description: "Picasso, Warhol, Pollock, Dalí. Uma das coleções de arte moderna mais importantes.",
        cost: 25,
      },
      {
        title: "High Line e Chelsea Market",
        type: "ACTIVITY",
        day: 4,
        startTime: "14:30",
        endTime: "17:30",
        location: "High Line",
        address: "High Line, New York",
        description: "Parque linear elevado sobre linha férrea desativada. Chelsea Market para petiscos.",
        cost: 0,
      },
      {
        title: "One World Observatory",
        type: "ACTIVITY",
        day: 5,
        startTime: "09:00",
        endTime: "11:00",
        location: "One World Trade Center",
        address: "285 Fulton St, New York",
        description: "Vista 360° do topo do edifício mais alto do hemisfério ocidental.",
        cost: 42,
      },
      {
        title: "Compras na 5th Avenue",
        type: "ACTIVITY",
        day: 5,
        startTime: "13:00",
        endTime: "16:00",
        location: "5th Avenue",
        address: "5th Ave, Midtown, New York",
        description: "Apple Store, Saks, Tiffany & Co., Bergdorf Goodman — a rua mais cara do mundo.",
        cost: 0,
      },
    ],
  },
  {
    id: "rome-history",
    title: "Roma Histórica",
    destination: "Roma, Itália",
    country: "Itália",
    continent: "Europa",
    flag: "🇮🇹",
    duration: 5,
    coverImage: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=500&fit=crop",
    description: "Explore a Cidade Eterna: dois milênios de história, arte renascentista, gelato e a culinária italiana mais autêntica.",
    tags: ["história", "arte", "gastronomia", "religião", "arquitetura"],
    highlights: [
      "Coliseu Romano",
      "Vaticano e Sistina",
      "Fontana di Trevi",
      "Fórum Romano",
    ],
    currency: "EUR",
    estimatedBudget: "€1.200 – €2.000",
    activities: [
      {
        title: "Coliseu e Fórum Romano",
        type: "ACTIVITY",
        day: 1,
        startTime: "09:00",
        endTime: "13:00",
        location: "Colosseum",
        address: "Piazza del Colosseo, Roma",
        description: "O anfiteatro mais famoso do mundo. Reserve online para pular a fila.",
        cost: 18,
      },
      {
        title: "Gelato artesanal",
        type: "MEAL",
        day: 1,
        startTime: "13:30",
        endTime: "14:00",
        location: "Giolitti",
        address: "Via degli Uffici del Vicario 40, Roma",
        description: "Gelateria histórica desde 1900 — imperdível para um gelato de pistache.",
        cost: 4,
      },
      {
        title: "Vaticano e Museus Vaticanos",
        type: "ACTIVITY",
        day: 2,
        startTime: "08:00",
        endTime: "13:00",
        location: "Vatican Museums",
        address: "Viale Vaticano, Roma",
        description: "Museus Vaticanos, Capela Sistina e Basílica de São Pedro. Reserve meses antes.",
        cost: 35,
      },
      {
        title: "Piazza Navona",
        type: "ACTIVITY",
        day: 2,
        startTime: "15:00",
        endTime: "17:00",
        location: "Piazza Navona",
        address: "Piazza Navona, Roma",
        description: "Praça barroca com a Fontana dei Quattro Fiumi de Bernini. Artistas de rua.",
        cost: 0,
      },
      {
        title: "Fontana di Trevi",
        type: "ACTIVITY",
        day: 3,
        startTime: "07:00",
        endTime: "08:30",
        location: "Fontana di Trevi",
        address: "Piazza di Trevi, Roma",
        description: "Vá cedo para a famosa fonte. Jogue uma moeda para voltar a Roma.",
        cost: 0,
      },
      {
        title: "Galleria Borghese",
        type: "ACTIVITY",
        day: 3,
        startTime: "09:00",
        endTime: "11:00",
        location: "Borghese Gallery",
        address: "Piazzale Scipione Borghese 5, Roma",
        description: "Esculturas de Bernini e pinturas de Caravaggio. Acesso com horário marcado.",
        cost: 20,
      },
      {
        title: "Trastevere — jantar típico",
        type: "MEAL",
        day: 3,
        startTime: "19:30",
        endTime: "22:00",
        location: "Trastevere",
        address: "Trastevere, Roma",
        description: "Bairro boêmio com trattorias autênticas. Experimente cacio e pepe e carbonara.",
        cost: 35,
      },
      {
        title: "Castel Sant'Angelo",
        type: "ACTIVITY",
        day: 4,
        startTime: "10:00",
        endTime: "12:30",
        location: "Castel Sant'Angelo",
        address: "Lungotevere Castello 50, Roma",
        description: "Fortaleza medieval com vista panorâmica do Tibre e da cidade.",
        cost: 15,
      },
      {
        title: "Via Appia Antica",
        type: "ACTIVITY",
        day: 4,
        startTime: "14:00",
        endTime: "17:00",
        location: "Via Appia Antica",
        address: "Via Appia Antica, Roma",
        description: "Passeio na estrada romana mais antiga. Catacumbas de São Callisto.",
        cost: 10,
      },
      {
        title: "Mercado Campo de' Fiori",
        type: "ACTIVITY",
        day: 5,
        startTime: "09:00",
        endTime: "11:00",
        location: "Campo de' Fiori",
        address: "Campo de' Fiori, Roma",
        description: "Mercado de frutas e legumes histórico. Ideal para comprar lembranças.",
        cost: 0,
      },
    ],
  },
  {
    id: "barcelona-art",
    title: "Barcelona de Gaudí",
    destination: "Barcelona, Espanha",
    country: "Espanha",
    continent: "Europa",
    flag: "🇪🇸",
    duration: 4,
    coverImage: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&h=500&fit=crop",
    description: "A cidade de Gaudí combina arquitetura modernista única, praias mediterrâneas, tapas e uma vibrante vida noturna.",
    tags: ["arquitetura", "praia", "gastronomia", "arte", "noturno"],
    highlights: [
      "Sagrada Família",
      "Parque Güell",
      "La Boqueria",
      "Barceloneta",
    ],
    currency: "EUR",
    estimatedBudget: "€900 – €1.500",
    activities: [
      {
        title: "Sagrada Família",
        type: "ACTIVITY",
        day: 1,
        startTime: "09:00",
        endTime: "12:00",
        location: "Sagrada Família",
        address: "Carrer de Mallorca 401, Barcelona",
        description: "A obra-prima inacabada de Gaudí. Reserve com torres para a melhor experiência.",
        cost: 35,
      },
      {
        title: "Casa Batlló",
        type: "ACTIVITY",
        day: 1,
        startTime: "14:00",
        endTime: "16:00",
        location: "Casa Batlló",
        address: "Passeig de Gràcia 43, Barcelona",
        description: "Fachada de azulejos que imita um dragão. Experiência imersiva com realidade aumentada.",
        cost: 40,
      },
      {
        title: "La Boqueria",
        type: "MEAL",
        day: 2,
        startTime: "09:00",
        endTime: "10:30",
        location: "Mercat de la Boqueria",
        address: "La Rambla 91, Barcelona",
        description: "Mercado coberto icônico com frutas tropicais, jamón ibérico e mariscos.",
        cost: 15,
      },
      {
        title: "Parque Güell",
        type: "ACTIVITY",
        day: 2,
        startTime: "11:00",
        endTime: "13:30",
        location: "Parque Güell",
        address: "08024 Barcelona",
        description: "Jardim público com mosaicos coloridos e terraço com vista da cidade.",
        cost: 13,
      },
      {
        title: "Barceloneta — praia",
        type: "ACTIVITY",
        day: 2,
        startTime: "15:00",
        endTime: "18:00",
        location: "Praia Barceloneta",
        address: "Barceloneta, Barcelona",
        description: "Praia urbana mais famosa de Barcelona. Mergulho no Mediterrâneo.",
        cost: 0,
      },
      {
        title: "Bairro Gótico",
        type: "ACTIVITY",
        day: 3,
        startTime: "10:00",
        endTime: "13:00",
        location: "Gothic Quarter",
        address: "Barri Gòtic, Barcelona",
        description: "Centro histórico medieval com a Catedral de Barcelona e ruínas romanas.",
        cost: 0,
      },
      {
        title: "Tapas no Mercado de Santa Caterina",
        type: "MEAL",
        day: 3,
        startTime: "13:30",
        endTime: "15:00",
        location: "Mercat de Santa Caterina",
        address: "Av. de Francesc Cambó 16, Barcelona",
        description: "Tapas variadas: patatas bravas, croquetas, pan con tomate.",
        cost: 25,
      },
      {
        title: "Palau de la Música Catalana",
        type: "EVENT",
        day: 4,
        startTime: "10:00",
        endTime: "11:30",
        location: "Palau de la Música Catalana",
        address: "C/ de Palau de la Música 4-6, Barcelona",
        description: "Obra-prima do modernismo catalão de Domènech i Montaner. Patrimônio UNESCO.",
        cost: 22,
      },
      {
        title: "Tibidabo e vista panorâmica",
        type: "ACTIVITY",
        day: 4,
        startTime: "15:00",
        endTime: "18:00",
        location: "Tibidabo",
        address: "Plaça del Tibidabo 3-4, Barcelona",
        description: "Ponto mais alto de Barcelona com parque de diversões e vista 360°.",
        cost: 15,
      },
    ],
  },
  {
    id: "dubai-luxury",
    title: "Dubai de Luxo",
    destination: "Dubai, Emirados Árabes",
    country: "Emirados Árabes Unidos",
    continent: "Oriente Médio",
    flag: "🇦🇪",
    duration: 4,
    coverImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=500&fit=crop",
    description: "Uma cidade-estado que desafia a gravidade: arranha-céus recordes, deserto árabe, ilhas artificiais e shoppings extravagantes.",
    tags: ["luxo", "arquitetura", "deserto", "compras", "futurismo"],
    highlights: [
      "Burj Khalifa",
      "Dubai Mall",
      "Deserto do Saara",
      "Palm Jumeirah",
    ],
    currency: "AED",
    estimatedBudget: "AED 4.000 – 8.000",
    activities: [
      {
        title: "Burj Khalifa — At the Top",
        type: "ACTIVITY",
        day: 1,
        startTime: "18:00",
        endTime: "20:00",
        location: "Burj Khalifa",
        address: "1 Sheikh Mohammed bin Rashid Blvd, Dubai",
        description: "Suba ao 124.º andar do edifício mais alto do mundo ao pôr do sol.",
        cost: 150,
      },
      {
        title: "Dubai Fountain Show",
        type: "EVENT",
        day: 1,
        startTime: "20:30",
        endTime: "21:30",
        location: "Dubai Fountain",
        address: "Burj Khalifa Lake, Downtown Dubai",
        description: "O maior show de fontes do mundo com música e luzes. Gratuito ao redor do lago.",
        cost: 0,
      },
      {
        title: "Dubai Mall",
        type: "ACTIVITY",
        day: 2,
        startTime: "10:00",
        endTime: "13:00",
        location: "The Dubai Mall",
        address: "Financial Centre Rd, Dubai",
        description: "Um dos maiores shoppings do mundo: aquário, pista de patinação, 1.200 lojas.",
        cost: 0,
      },
      {
        title: "Safari no Deserto",
        type: "ACTIVITY",
        day: 2,
        startTime: "15:00",
        endTime: "21:00",
        location: "Dubai Desert",
        address: "Al Awir Desert, Dubai",
        description: "Dune bashing, passeio de camelo, falcoaria, jantar beduíno no acampamento.",
        cost: 120,
      },
      {
        title: "Palm Jumeirah e Atlantis",
        type: "ACTIVITY",
        day: 3,
        startTime: "10:00",
        endTime: "13:00",
        location: "Palm Jumeirah",
        address: "Palm Jumeirah, Dubai",
        description: "Ilha artificial em forma de palmeira. Monorail e vista do Atlantis The Palm.",
        cost: 10,
      },
      {
        title: "Dubai Creek e Al Fahidi",
        type: "ACTIVITY",
        day: 3,
        startTime: "15:00",
        endTime: "18:00",
        location: "Al Fahidi Historical Neighbourhood",
        address: "Al Fahidi, Bur Dubai",
        description: "Bairro histórico com museu e abra (barco tradicional) no Creek.",
        cost: 5,
      },
      {
        title: "Museum of the Future",
        type: "ACTIVITY",
        day: 4,
        startTime: "09:00",
        endTime: "12:00",
        location: "Museum of the Future",
        address: "Sheikh Zayed Rd, Dubai",
        description: "Experiência imersiva no edifício mais bonito do mundo segundo a ONU.",
        cost: 150,
      },
      {
        title: "Jantar de Despedida",
        type: "MEAL",
        day: 4,
        startTime: "19:00",
        endTime: "21:30",
        location: "At.mosphere",
        address: "Burj Khalifa, Level 122, Dubai",
        description: "Restaurante mais alto do mundo com jantar formal e vista noturna deslumbrante.",
        cost: 200,
      },
    ],
  },
  {
    id: "bali-spiritual",
    title: "Bali Espiritual",
    destination: "Bali, Indonésia",
    country: "Indonésia",
    continent: "Ásia",
    flag: "🇮🇩",
    duration: 7,
    coverImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=500&fit=crop",
    description: "A ilha dos deuses combina templos hinduístas, terraços de arroz, surf, gastronomia orgânica e uma espiritualidade única.",
    tags: ["espiritualidade", "natureza", "surf", "ioga", "cultura"],
    highlights: [
      "Terraços de Arroz de Tegalalang",
      "Templo Tanah Lot",
      "Ubud e mercado artesanal",
      "Pôr do sol em Seminyak",
    ],
    currency: "IDR",
    estimatedBudget: "IDR 8.000.000 – 15.000.000",
    activities: [
      {
        title: "Chegada e relaxamento em Seminyak",
        type: "OTHER",
        day: 1,
        startTime: "14:00",
        endTime: "18:00",
        location: "Seminyak Beach",
        address: "Seminyak, Bali",
        description: "Chegada, check-in e primeiro mergulho na vibrante Seminyak.",
      },
      {
        title: "Pôr do sol em Tanah Lot",
        type: "ACTIVITY",
        day: 1,
        startTime: "17:00",
        endTime: "19:00",
        location: "Tanah Lot Temple",
        address: "Beraban, Kediri, Tabanan Regency, Bali",
        description: "Templo sobre rocha no oceano — pôr do sol mais fotogênico de Bali.",
        cost: 60000,
      },
      {
        title: "Aula de ioga em Ubud",
        type: "ACTIVITY",
        day: 2,
        startTime: "08:00",
        endTime: "10:00",
        location: "The Yoga Barn",
        address: "Gang Gagak, Ubud, Bali",
        description: "Centro de ioga e bem-estar mais famoso de Bali. Vários estilos de prática.",
        cost: 130000,
      },
      {
        title: "Terraços de Arroz de Tegalalang",
        type: "ACTIVITY",
        day: 2,
        startTime: "07:00",
        endTime: "10:00",
        location: "Tegalalang Rice Terrace",
        address: "Jl. Raya Tegalalang, Ubud, Bali",
        description: "Iconic terraços de arroz com swing instagramável e cafés com vista.",
        cost: 20000,
      },
      {
        title: "Mercado de Ubud",
        type: "ACTIVITY",
        day: 2,
        startTime: "11:00",
        endTime: "13:00",
        location: "Ubud Traditional Market",
        address: "Jl. Raya Ubud, Bali",
        description: "Artesanato local, tecidos, lembranças. Pechinche com simpatia.",
        cost: 0,
      },
      {
        title: "Templo Besakih — Mãe de todos os templos",
        type: "ACTIVITY",
        day: 3,
        startTime: "09:00",
        endTime: "13:00",
        location: "Besakih Temple",
        address: "Besakih, Rendang, Karangasem Regency, Bali",
        description: "Maior e mais sagrado templo de Bali no sopé do vulcão Agung.",
        cost: 150000,
      },
      {
        title: "Vulcão Batur ao amanhecer",
        type: "ACTIVITY",
        day: 4,
        startTime: "02:00",
        endTime: "09:00",
        location: "Mount Batur",
        address: "Kintamani, Bangli Regency, Bali",
        description: "Caminhada noturna guiada para assistir o nascer do sol do vulcão ativo.",
        cost: 350000,
      },
      {
        title: "Pura Tirta Empul — banho sagrado",
        type: "ACTIVITY",
        day: 4,
        startTime: "11:00",
        endTime: "13:00",
        location: "Tirta Empul Temple",
        address: "Jl. Tirta, Tampaksiring, Bali",
        description: "Templo com nascente sagrada. Participe do ritual de purificação com água benta.",
        cost: 50000,
      },
      {
        title: "Aula de culinária balinesa",
        type: "ACTIVITY",
        day: 5,
        startTime: "09:00",
        endTime: "13:00",
        location: "Paon Bali Cooking Class",
        address: "Ubud, Bali",
        description: "Visite mercado, colha ingredientes e aprenda a fazer nasi goreng, satay e rendang.",
        cost: 250000,
      },
      {
        title: "Kecak Dance no Uluwatu",
        type: "EVENT",
        day: 5,
        startTime: "18:00",
        endTime: "20:00",
        location: "Uluwatu Temple",
        address: "Pecatu, South Kuta, Badung Regency, Bali",
        description: "Dança ritual kecak ao pôr do sol no penhasco mais dramático de Bali.",
        cost: 150000,
      },
      {
        title: "Surf em Kuta",
        type: "ACTIVITY",
        day: 6,
        startTime: "07:00",
        endTime: "11:00",
        location: "Kuta Beach",
        address: "Kuta, Bali",
        description: "Lição de surf na melhor praia de iniciantes de Bali. Instrutores certificados.",
        cost: 200000,
      },
      {
        title: "Spa e massagem tradicional",
        type: "ACTIVITY",
        day: 7,
        startTime: "14:00",
        endTime: "17:00",
        location: "Jari Menari",
        address: "Jl. Raya Basangkasa 47, Seminyak, Bali",
        description: "Massagem balinesa autêntica com técnicas rituais. Um dos melhores spas de Bali.",
        cost: 250000,
      },
    ],
  },
  {
    id: "lisbon-charm",
    title: "Lisboa Encantadora",
    destination: "Lisboa, Portugal",
    country: "Portugal",
    continent: "Europa",
    flag: "🇵🇹",
    duration: 4,
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
    description: "A capital mais ocidental da Europa seduz com seus miradouros, elétricos amarelos, pastéis de nata e a melancolica alma do fado.",
    tags: ["história", "gastronomia", "fado", "miradores", "passeios"],
    highlights: [
      "Elétrico 28 por Alfama",
      "Mosteiro dos Jerónimos",
      "Pastéis de Belém",
      "Fado em Alfama",
    ],
    currency: "EUR",
    estimatedBudget: "€700 – €1.200",
    activities: [
      {
        title: "Elétrico 28 e Bairro de Alfama",
        type: "ACTIVITY",
        day: 1,
        startTime: "10:00",
        endTime: "13:00",
        location: "Alfama",
        address: "Alfama, Lisboa",
        description: "Suba no elétrico 28 e explore o bairro mais antigo de Lisboa com suas ruelas.",
        cost: 3,
      },
      {
        title: "Castelo de São Jorge",
        type: "ACTIVITY",
        day: 1,
        startTime: "14:00",
        endTime: "16:30",
        location: "Castelo de São Jorge",
        address: "R. de Santa Cruz do Castelo, Lisboa",
        description: "Fortaleza moura com vista panorâmica de Lisboa e do Rio Tejo.",
        cost: 15,
      },
      {
        title: "Fado ao vivo em Alfama",
        type: "EVENT",
        day: 1,
        startTime: "21:00",
        endTime: "23:30",
        location: "Tasca do Chico",
        address: "R. do Diário de Notícias 39, Lisboa",
        description: "Casa de fado intimista com fadistas que cantam de coração. Reserve.",
        cost: 30,
      },
      {
        title: "Mosteiro dos Jerónimos",
        type: "ACTIVITY",
        day: 2,
        startTime: "09:00",
        endTime: "11:30",
        location: "Mosteiro dos Jerónimos",
        address: "Largo do Impeiro, Belém, Lisboa",
        description: "Obra-prima do Manuelino. Patrimônio UNESCO. Sepultura de Vasco da Gama.",
        cost: 12,
      },
      {
        title: "Pastéis de Belém",
        type: "MEAL",
        day: 2,
        startTime: "12:00",
        endTime: "13:00",
        location: "Pastéis de Belém",
        address: "R. de Belém 84, Lisboa",
        description: "A receita original dos pastéis de nata desde 1837. Coma quente com canela.",
        cost: 5,
      },
      {
        title: "Torre de Belém",
        type: "ACTIVITY",
        day: 2,
        startTime: "14:00",
        endTime: "15:30",
        location: "Torre de Belém",
        address: "Av. Brasília, Lisboa",
        description: "Ícone da era dos descobrimentos às margens do Tejo. Patrimônio UNESCO.",
        cost: 10,
      },
      {
        title: "Mercado da Ribeira",
        type: "MEAL",
        day: 3,
        startTime: "12:00",
        endTime: "14:00",
        location: "Mercado da Ribeira",
        address: "Av. 24 de Julho 49, Lisboa",
        description: "Time Out Market Lisboa: os melhores chefs da cidade num só espaço.",
        cost: 20,
      },
      {
        title: "Sintra — Palácio da Pena",
        type: "ACTIVITY",
        day: 3,
        startTime: "15:00",
        endTime: "19:00",
        location: "Palácio da Pena",
        address: "Estrada da Pena, Sintra",
        description: "Palácio de conto de fadas colorido no topo da montanha. Património UNESCO.",
        cost: 20,
      },
      {
        title: "Miradouro da Graça",
        type: "ACTIVITY",
        day: 4,
        startTime: "07:00",
        endTime: "08:30",
        location: "Miradouro da Graça",
        address: "Largo da Graça, Lisboa",
        description: "Melhor miradouro para o nascer do sol em Lisboa. Poucos turistas de manhã cedo.",
        cost: 0,
      },
      {
        title: "Bairro de Chiado e compras",
        type: "ACTIVITY",
        day: 4,
        startTime: "10:00",
        endTime: "13:00",
        location: "Chiado",
        address: "Chiado, Lisboa",
        description: "Bairro cultural com livraria Bertrand (mais antiga do mundo), cafés e boutiques.",
        cost: 0,
      },
    ],
  },
  {
    id: "amsterdam-canals",
    title: "Amsterdã dos Canais",
    destination: "Amsterdã, Holanda",
    country: "Holanda",
    continent: "Europa",
    flag: "🇳🇱",
    duration: 4,
    coverImage: "https://images.unsplash.com/photo-1534351590666-13e3e96b5702?w=800&h=500&fit=crop",
    description: "A Veneza do norte: canais pitorescas, museus excepcionais, bicicletas por todos os lados e uma cultura aberta e cosmopolita.",
    tags: ["canais", "museus", "arte", "bicicleta", "cultura"],
    highlights: [
      "Museu Van Gogh",
      "Anne Frank Huis",
      "Passeio de barco pelos canais",
      "Rijksmuseum",
    ],
    currency: "EUR",
    estimatedBudget: "€900 – €1.500",
    activities: [
      {
        title: "Passeio de barco pelos canais",
        type: "ACTIVITY",
        day: 1,
        startTime: "14:00",
        endTime: "16:00",
        location: "Canal Ring",
        address: "Centraal Station, Amsterdam",
        description: "Canais inscritos no Patrimônio UNESCO. Veja casas estreitas do século XVII.",
        cost: 25,
      },
      {
        title: "Rijksmuseum",
        type: "ACTIVITY",
        day: 1,
        startTime: "17:00",
        endTime: "20:00",
        location: "Rijksmuseum",
        address: "Museumstraat 1, Amsterdam",
        description: "Maior museu dos Países Baixos: Vermeer, Rembrandt, Hals. A Ronda Noturna.",
        cost: 22,
      },
      {
        title: "Anne Frank Huis",
        type: "ACTIVITY",
        day: 2,
        startTime: "09:00",
        endTime: "11:00",
        location: "Anne Frank House",
        address: "Prinsengracht 263, Amsterdam",
        description: "Casa onde Anne Frank escondeu-se da perseguição nazista. Muito emocionante.",
        cost: 16,
      },
      {
        title: "Museu Van Gogh",
        type: "ACTIVITY",
        day: 2,
        startTime: "12:00",
        endTime: "15:00",
        location: "Van Gogh Museum",
        address: "Museumplein 6, Amsterdam",
        description: "A maior coleção de obras de Van Gogh do mundo. Noite Estrelada e Girassóis.",
        cost: 25,
      },
      {
        title: "Passeio de bicicleta pelo Jordaan",
        type: "ACTIVITY",
        day: 3,
        startTime: "10:00",
        endTime: "13:00",
        location: "Jordaan",
        address: "Jordaan, Amsterdam",
        description: "Bairro de galeries, cafés marrons e mercado do Noordermarkt aos sábados.",
        cost: 15,
      },
      {
        title: "Keukenhof — jardim de tulipas",
        type: "ACTIVITY",
        day: 3,
        startTime: "09:00",
        endTime: "14:00",
        location: "Keukenhof Gardens",
        address: "Stationsweg 166A, Lisse",
        description: "Maior jardim de flores do mundo. Aberto de março a maio. 7 milhões de bulbos.",
        cost: 22,
      },
      {
        title: "Heineken Experience",
        type: "ACTIVITY",
        day: 4,
        startTime: "11:00",
        endTime: "13:30",
        location: "Heineken Experience",
        address: "Stadhouderskade 78, Amsterdam",
        description: "Tour interativo na cervejaria histórica da Heineken com degustação.",
        cost: 23,
      },
      {
        title: "Vondelpark e despedida",
        type: "ACTIVITY",
        day: 4,
        startTime: "15:00",
        endTime: "17:00",
        location: "Vondelpark",
        address: "Vondelpark, Amsterdam",
        description: "Parque mais famoso de Amsterdã. Perfeito para um piquenique de despedida.",
        cost: 0,
      },
    ],
  },
  {
    id: "santorini-greek",
    title: "Santorini Grega",
    destination: "Santorini, Grécia",
    country: "Grécia",
    continent: "Europa",
    flag: "🇬🇷",
    duration: 4,
    coverImage: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&h=500&fit=crop",
    description: "A joia do Egeu: cúpulas azuis, pôres do sol avermelhados de Oia, vinhos locais e a história da antiga Thira.",
    tags: ["romântico", "natureza", "história", "gastronomia", "mar"],
    highlights: [
      "Pôr do sol em Oia",
      "Caldera de vulcão",
      "Praia de areia negra de Perissa",
      "Vila de Fira",
    ],
    currency: "EUR",
    estimatedBudget: "€1.000 – €2.000",
    activities: [
      {
        title: "Chegada e passeio em Fira",
        type: "ACTIVITY",
        day: 1,
        startTime: "14:00",
        endTime: "18:00",
        location: "Fira",
        address: "Fira, Santorini",
        description: "Capital da ilha com vista da caldera. Museu Arqueológico e lojas.",
        cost: 0,
      },
      {
        title: "Pôr do sol em Oia",
        type: "ACTIVITY",
        day: 1,
        startTime: "19:00",
        endTime: "21:00",
        location: "Oia",
        address: "Oia, Santorini",
        description: "O pôr do sol mais fotografado do mundo. Chegue cedo para garantir lugar.",
        cost: 0,
      },
      {
        title: "Praia Negra de Perissa",
        type: "ACTIVITY",
        day: 2,
        startTime: "10:00",
        endTime: "14:00",
        location: "Perissa Black Beach",
        address: "Perissa, Santorini",
        description: "Praia de areia vulcânica preta com águas cristalinas.",
        cost: 0,
      },
      {
        title: "Ancient Thira — ruínas gregas",
        type: "ACTIVITY",
        day: 2,
        startTime: "15:00",
        endTime: "17:30",
        location: "Ancient Thira",
        address: "Mesa Vouno, Santorini",
        description: "Sítio arqueológico com ruínas de 3.000 anos no topo do Monte Mesa Vouno.",
        cost: 8,
      },
      {
        title: "Degustação de vinhos em vinhedo",
        type: "ACTIVITY",
        day: 3,
        startTime: "11:00",
        endTime: "13:30",
        location: "Santo Wines Winery",
        address: "Pyrgos, Santorini",
        description: "Vinhos locais únicos: Assyrtiko e Vinsanto. Vista deslumbrante da caldera.",
        cost: 25,
      },
      {
        title: "Excursão à Caldera e Vulcão",
        type: "ACTIVITY",
        day: 3,
        startTime: "14:00",
        endTime: "19:00",
        location: "Nea Kameni Volcano",
        address: "Caldera de Santorini",
        description: "Barco até o vulcão ativo, fontes termais e ilhéu Thirassia.",
        cost: 40,
      },
      {
        title: "Oia — vielas e cafés",
        type: "ACTIVITY",
        day: 4,
        startTime: "09:00",
        endTime: "12:00",
        location: "Oia Village",
        address: "Oia, Santorini",
        description: "De manhã as ruelas brancas estão vazias. Perfeito para fotos e cafés.",
        cost: 0,
      },
      {
        title: "Akrotiri — Pompeia grega",
        type: "ACTIVITY",
        day: 4,
        startTime: "13:00",
        endTime: "15:30",
        location: "Akrotiri Archaeological Site",
        address: "Akrotiri, Santorini",
        description: "Cidade minoica preservada sob cinzas vulcânicas há 3.600 anos. Incrível.",
        cost: 14,
      },
    ],
  },
];

export function getTemplateById(id: string): RouteTemplate | undefined {
  return ROUTE_TEMPLATES.find((t) => t.id === id);
}
